export enum Fields {
  AGGREGATE_TIME_SPENT = 'aggregatetimespent',
  ASSIGNEE = 'assignee',
  CREATED = 'created',
  CREATOR = 'creator',
  ESTIMATION = 'customfield_10016',
  ISSUE_TYPE = 'issuetype',
  KEY = 'key',
  PARENT = 'parent',
  PRIORITY = 'priority',
  PRODUCT = 'customfield_10249',
  REPORTER = 'reporter',
  RESOLUTION = 'resolution',
  RESOLUTION_DATE = 'resolutiondate',
  SPRINTS = 'customfield_10021',
  STATUS = 'status',
  STATUS_CATEGORY_CHANGEDATE = 'statuscategorychangedate',
  SUMMARY = 'summary',
  SUPPORT_DISCOVERED_BY = 'customfield_10252',
  SUPPORT_RESOLUTION_TYPE = 'customfield_10253',
  SUPPORT_ROOT_CAUSE = 'customfield_10035',
}
