import { format } from 'date-fns';

export enum Columns {
  ID = 'ID',
  TYPE = 'TYPE',
  TYPE_NORMALIZED = 'TYPE_NORMALIZED',
  PROJECT_KEY = 'PROJECT_KEY',
  PROJECT_NAME = 'PROJECT_NAME',
  KEY = 'KEY',
  STATUS = 'STATUS',
  SUMMARY = 'SUMMARY',
  ESTIMATION = 'ESTIMATION',
  TIME_SPENT = 'TIME_SPENT',
  TIME_SPENT_HOURS = 'TIME_SPENT_HOURS',
  TIME_SPENT_DAYS = 'TIME_SPENT_DAYS',
  REPORTER = 'REPORTER',
  ASSIGNEE = 'ASSIGNEE',
  ASSIGNEE_SENIORITY = 'ASSIGNEE_SENIORITY',
  ASSIGNEE_ROLE = 'ASSIGNEE_ROLE',
  CREATED_AT = 'CREATED_AT',
  STARTED_AT = 'STARTED_AT',
  RESOLVED_AT = 'RESOLVED_AT',
  PRIORITY = 'PRIORITY',
  EPIC_KEY = 'EPIC_KEY',
  EPIC_SUMMARY = 'EPIC_SUMMARY',
  EPIC_LABEL = 'EPIC_LABEL',
  EPIC_STATUS = 'EPIC_STATUS',
  EPIC_LINK = 'EPIC_LINK',
  LINK = 'LINK',
  SUPPORT_DISCOVERED_BY = 'SUPPORT_DISCOVERED_BY',
  SUPPORT_RESOLUTION_TYPE = 'SUPPORT_RESOLUTION_TYPE',
  SUPPORT_PRODUCT = 'SUPPORT_PRODUCT',

  IS_STARTED = 'IS_STARTED',
  IS_DELIVERED = 'IS_DELIVERED',
  IS_IN_PROGRESS = 'IS_IN_PROGRESS',

  // Created
  CREATED_SPRINT = 'CREATED_SPRINT',
  CREATED_WEEK = 'CREATED_WEEK',
  CREATED_MONTH = 'CREATED_MONTH',
  CREATED_QUARTER = 'CREATED_QUARTER',
  CREATED_SEMESTER = 'CREATED_SEMESTER',

  // Starting of work
  STARTED_SPRINT = 'STARTED_SPRINT',
  STARTED_WEEK = 'STARTED_WEEK',
  STARTED_MONTH = 'STARTED_MONTH',
  STARTED_QUARTER = 'STARTED_QUARTER',
  STARTED_SEMESTER = 'STARTED_SEMESTER',

  // Resolved
  RESOLVED_SPRINT = 'RESOLVED_SPRINT',
  RESOLVED_WEEK = 'RESOLVED_WEEK',
  RESOLVED_MONTH = 'RESOLVED_MONTH',
  RESOLVED_QUARTER = 'RESOLVED_QUARTER',
  RESOLVED_SEMESTER = 'RESOLVED_SEMESTER',

  // Duration of a task
  LEAD_TIME_SECONDS = 'LEAD_TIME_SECONDS',
  LEAD_TIME_HOURS = 'LEAD_TIME_HOURS',
  LEAD_TIME_DAYS = 'LEAD_TIME_DAYS',
  LEAD_TIME_DAYS_BUCKET = 'LEAD_TIME_DAYS_BUCKET',

  LEAD_TIME_BUSINESS_SECONDS = 'LEAD_TIME_BUSINESS_SECONDS',
  LEAD_TIME_BUSINESS_HOURS = 'LEAD_TIME_BUSINESS_HOURS',
  LEAD_TIME_BUSINESS_DAYS = 'LEAD_TIME_BUSINESS_DAYS',
  LEAD_TIME_BUSINESS_DAYS_BUCKET = 'LEAD_TIME_BUSINESS_DAYS_BUCKET',

  // statuses duration
  STATUS_DURATION_DAYS_TODO = 'STATUS_DURATION_DAYS_TODO',
  STATUS_BUSINESS_DURATION_DAYS_TODO = 'STATUS_BUSINESS_DURATION_DAYS_TODO',
  STATUS_DURATION_DAYS_HOLD = 'STATUS_DURATION_DAYS_HOLD',
  STATUS_BUSINESS_DURATION_DAYS_HOLD = 'STATUS_BUSINESS_DURATION_DAYS_HOLD',
  STATUS_DURATION_DAYS_IN_PROGRESS = 'STATUS_DURATION_DAYS_IN_PROGRESS',
  STATUS_BUSINESS_DURATION_DAYS_IN_PROGRESS = 'STATUS_BUSINESS_DURATION_DAYS_IN_PROGRESS',
  STATUS_DURATION_DAYS_QA = 'STATUS_DURATION_DAYS_QA',
  STATUS_BUSINESS_DURATION_DAYS_QA = 'STATUS_BUSINESS_DURATION_DAYS_QA',
  PRODUCT_PRIORITY = 'PRODUCT_PRIORITY',
  EFFORT_DAYS = 'EFFORT_DAYS',
  EFFORT = 'EFFORT',
  ESTIMATION_CONFIDENCE = 'CONFIDENCE',
}
